### ISSUE TITLE
Used wrong OAuth Credentials

### ISSUE THREAD

**Issue by w1ns0ck** [Daanoz/ha-google-photos#20]
Hello,

I was setting this up last night and in my tired state of mind, I accidently tried to link it to the wrong Google OAuth Credentials. Now when I try to redo the setup process it automatically links to the wrong creds and gives me the "Access blocked: This app’s request is invalid".

I have uninstalled the integration manually and via HA UI. I even tried to reset the OAuth credentials in the Google Cloud page, and nothing is allowing me to redo the OAuth Credential setup. 

Any Ideas?

Version: v0.5.0

**Comment by Daanoz** [comment]
> If you navigate to https://`your_ha_instance`/config/application_credentials (or click the 3 dot menu on the integrations screen) you can delete the credentials, and it will ask for new credentials when setting up the integration.
