### ISSUE TITLE
Change credentials (client ID & Client Secret) #Question

### ISSUE THREAD

**Issue by RodriLara** [Daanoz/ha-google-photos#21]
I submitted by error different google API credentials, it means, another client ID & Client Secret. 
If you desinstall and re install the integration, in somewhere was saved the credentials and it's not possible to update to the correct ones.

Now when I search the NEW integration and select google photos, this is the first page:
![image](https://user-images.githubusercontent.com/38332780/230735488-af44a735-d8fd-460a-bc00-822938d86f5e.png)

and, of course, since the project is incorrect (this project has been deleted), google returns an error:
![image](https://user-images.githubusercontent.com/38332780/230735562-b57ee829-86b8-4649-bfdf-8e1cf6229396.png)

what I want to do is to have the original first page when credentials are requested and insert now the correct Client ID & Client Secret.

**Comment by Daanoz** [comment]
If you navigate to https://`your_ha_instance`/config/application_credentials (or click the 3 dot menu on the integrations screen) you can delete the credentials, and it will ask for new credentials when setting up the integration.

**Comment by Daanoz** [comment]
I have also added this to the readme for future reference: [FAQ](https://github.com/Daanoz/ha-google-photos#how-can-i-change-my-credentials--i-entered-the-wrong-credentials-now-what)
