### ISSUE TITLE
Add location info

### ISSUE THREAD

**Issue by LukaszP2** [Daanoz/ha-google-photos#24]
I will be great to have location info in attribiutes. Can you add this?

**Comment by Daanoz** [comment]
Sadly, this is not possible... The Google api doesn't expose location information, and the exif information has been stripped from any location details.

**Comment by LukaszP2** [comment]
Oh... It's not good news...

**Comment by Daanoz** [comment]
Yeah indeed. If you want, you can voice your opinion with the others, but don't expect it to change soon.

https://issuetracker.google.com/issues/80379228
