### ISSUE TITLE
Improve fallback resolution in Original mode

### ISSUE THREAD

**Issue by amondit** [Daanoz/ha-google-photos#27]
Hello,

I've experienced a strange behavior when using "Original" mode. On "Crop" mode it seems fine, pictures get cropped at the view container size, however on "Original" mode, pictures get resized to either the fallback width or height  values (1024 x 512 px) ([values in code](https://github.com/Daanoz/ha-google-photos/blob/main/custom_components/google_photos/coordinator.py#LL252C3-L253C1). This leads to seriously blurry pictures.

I tried manually changing the values to 3000x3000 just to test, and indeed it now generates much clearer pictures.

Do you think it might be a good idea to increase these fallback values or would there be a reason not to?

Thanks a lot!

**Comment by Daanoz** [comment]
I'm not able to reproduce this, could you share your dashboard configuration where it happens?

**Comment by Daanoz** [comment]
I'm guessing it's the same problem as mentioned in the [issue](https://github.com/Daanoz/ha-google-photos#lovelace-wall-panel) you also replied too at the lovelave-wallpanel repo? 

I have [replied](https://github.com/j-a-n/lovelace-wallpanel/issues/118#issuecomment-1597733658) there with an explanation what happens, feel free to reopen if this doesn't solve your issue.
