### ISSUE TITLE
Migrate to new Image Entity

### ISSUE THREAD

**Issue by stboch** [Daanoz/ha-google-photos#33]
**Is your feature request related to a problem? Please describe.**
Home-Assistant 2023.7 added support for Image Entity... 
https://www.home-assistant.io/blog/2023/07/05/release-20237/#image-entities

**Describe the solution you'd like**
Migrate from Camera entity to image entitty. Hopefully this will reduce complexity and allow for new cooler features going forward.

**Comment by Daanoz** [comment]
I looked into this, the main issue here is that the [call](https://github.com/home-assistant/core/blob/aea2fc68e78826fef534d73c017c2dc0e25621b7/homeassistant/components/image/__init__.py#L72) to retrieve the image is not provided with the contextual dimensions. This would basically force the integration to always give back the highest resolution image without any cropping possibilities.  Also if I every get to implementing the retrieval of videos, this would probably not work with the image entity.

All in all, only downsides at the moment, but willing to revisit this once there is an nice use case.
