### ISSUE TITLE
Get access to all the Albums as one entity

### ISSUE THREAD

**Issue by auredor** [Daanoz/ha-google-photos#34]
**Is your feature request related to a problem? Please describe.**
As for now, we have to create one set of entities for each album if we want access different albums. And so, we've got lots of different lovelace card that we can show or hide but it's not very convinient. It should include also the shared albums.

**Describe the solution you'd like**
A unique set of entities for all the selected (at integratoin level) albums with different options for the next media :
- random through all the albums
- random through the current album, then  random through the next album  (randomly choosen or sorted by date, name...) and so one
- every picture of each album, then the same for the next album (randomly choosen or sorted by date, name...)
- random through the selected album only (using an helper to choose it)
- every picture of the selected album only (using an helper to choose it)

**Describe alternatives you've considered**

**Additional context**
 I don't use favorite. I prefer to create album for every occasions.

**Comment by balintbuzasi** [comment]
@Daanoz it'd be a great function, do you have it in your plans? thank's!

**Comment by Daanoz** [comment]
Not yet, it's not an easy thing to build. Google's API is quite limited, so I would need to figure out a way to build this without creating an enormous impact into the rate limits that Google has set for its API.

**Comment by balintbuzasi** [comment]
Thank you for your fast reply... I'm sad to read, because I store my pics in 150 albums :(
Anyway, it's a great integration :)

**Comment by Daanoz** [comment]
Due to API changes announced by Google, the integration will be deprecated on April 2025, so no new functionality will be added. https://github.com/Daanoz/ha-google-photos/issues/64
