### ISSUE TITLE
Not loading in HA 2023.8. 0b3

### ISSUE THREAD

**Issue by Bluhme1** [Daanoz/ha-google-photos#35]
Cannot load in the newest version (beta)

Get the following log:

Logger: homeassistant.setup
Source: setup.py:209
First occurred: 17.47.01 (1 occurrences)
Last logged: 17.47.01

Setup failed for custom integration google_photos: Requirements for google_photos not found: ['pillow>=9.1.1,<10.0.0'].

**Comment by psleutel** [comment]
Same problem here after upgrade to 2023.8.0

**Comment by un-listed** [comment]
Same problem here

**Comment by Daanoz** [comment]
Just released 0.6.1 which should solve it. Not the first time this issue came up (#6) so took a different approach, hopefully it stays away now.
