### ISSUE TITLE
error while creating account

### ISSUE THREAD

**Issue by mmikee02** [Daanoz/ha-google-photos#37]
Hello, 
I try to install the ha google photo plugin, 
I followed the github procedure, I created a client with id and secret code, activated api, ...
all was fine until the oauth screen :  when I click on my google account and accept the conditions, I receive this screen : 

[https://www.googleapis.com/auth/userinfo.email&authuser=0&prompt=consent]

**

> You are receiving this error either because your input OAuth2 scope name is invalid or it refers to a newer scope that is outside the domain of this legacy API.
> 
> This API was built at a time when the scope name format was not yet standardized. This is no longer the case and all valid scope names (both old and new) are catalogued at https://developers.google.com/identity/protocols/oauth2/scopes. Use that webpage to lookup (manually) the scope name associated with the API you are trying to call and use it to craft your OAuth2 request.

**

## Version of the custom_component
latest

Can someone tell me what I did wrong?
Thanks in advance, 
-->Michaël

**Comment by Daanoz** [comment]
It can be a bit tricky to debug these, could you verify that your setup looks like:

**OAuth consent screen setup**
![OAuth consent screen setup](https://github.com/Daanoz/ha-google-photos/raw/main/docs/OAuthConsentOverview.png)
**OAuth consent screen edit, step1**
![OAuth consent screen edit, step1](https://github.com/Daanoz/ha-google-photos/raw/main/docs/OAuthConsent1.png)
**OAuth consent screen edit, step2**
![OAuth consent screen edit, step2](https://github.com/Daanoz/ha-google-photos/raw/main/docs/OAuthConsent2.png)
**OAuth consent screen edit, step3**
![OAuth consent screen edit, step3](https://github.com/Daanoz/ha-google-photos/raw/main/docs/OAuthConsent3.png)
**OAuth consent screen edit, step4**
![OAuth consent screen edit, step4](https://github.com/Daanoz/ha-google-photos/raw/main/docs/OAuthConsent4.png)
**Credentials**
![Credentials](https://github.com/Daanoz/ha-google-photos/raw/main/docs/Credentials.png)
