### ISSUE TITLE
Include Location Information in Metadata if available

### ISSUE THREAD

**Issue by stephengolub** [Daanoz/ha-google-photos#38]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Nice integration! I'd like to be able to display _where_ a photo was taken on my dashboard. I see the metadata options and see the camera information. I've checked in Google Photos and the location information is available on the photos in question.

**Describe alternatives you've considered**
Doesn't seem to be any.

**Additional context**
N/A

**Comment by Daanoz** [comment]
See #24, Google holds back this data on purpose...
