### ISSUE TITLE
google photos unavailable

### ISSUE THREAD

**Issue by ca1p3** [Daanoz/ha-google-photos#40]
hi my google photos says that it is unavailable.
i have tried to restart home assistant without any luck.
it worked yesterday but today it dosent.

**Comment by bulldoguk** [comment]
Same here - worked last night, but today I have no photos and no error logs.  If I try to change the album, I get an error message that simply says "Error" - otherwise nothing.  Any pointers towards debugging this??

**Comment by bulldoguk** [comment]
So for what it's worth, I deleted the integration (including secrets) and readded it to Home Assistant.  I did NOT delete any files, just deleted  from the integrations screen, rebooted and then readded.  I had to re-enter my credentials, but now everything seems fine again.  I'll see how long it lasts...

**Comment by Daanoz** [comment]
Let me know if it re-occurs, you are not the first one to have an issue like this, but it's been hard to reproduce.

**Comment by janstadt** [comment]
I've been consistently getting this but i think its due to the rate limit/quota exceeding after restarts with HA. Is there any workaround here or something?
