### ISSUE TITLE
Access blocked: the request of this app is not valid

### ISSUE THREAD

**Issue by sonewtogithub** [Daanoz/ha-google-photos#42]
Solved : I could not reuse the old settings because that was not configured as a webapplication

I try to install this integration.

I allready had a google id with credentials for home assistant . So I added the google photo api to that.
After downloading the integration in home assistant and restarting HASS I want to add the integration.
When I add name and credentials I click continue. The error I get is : You cannot login because this app send a invalid request. Try again later or send a message to the developer about this problem.

Error:400: redirect_uri_mismatch

I am not sure I use the correct name, but I suppose I have to use  OAuth 2.0 Client IDs name ?
Tried the name on the Oauth consent screen too

Version Home assistant
Home Assistant 2023.9.2
Supervisor 2023.10.0
Operating System 10.5
Frontend 20230911.0 - latest
I am running Home Assistant on a virtual machine 

I am sorry when this topic does not meet all requirement to add a new issue but I am hoping this information is enough to solve this problem

**Comment by fefris** [comment]
You set the redirect_uri right?

https://my.home-assistant.io/redirect/oauth

**Comment by sonewtogithub** [comment]
See first line in topic
