### ISSUE TITLE
Resolution does not scale with pixel density, resulting in blurry pictures on high-density screens

### ISSUE THREAD

**Issue by JiDW** [Daanoz/ha-google-photos#45]
Hello!

I am using your (amazing) integration for my lovelace wallpanel screensaver on a Pixel Tablet.
I tried to troubleshoot why my pictures were blurry, and after some tests I believe it is because the integration is downloading pictures with a resolution based on the CSS resolution (1280x800) instead of the device pixel resolution (2560x1600)

I confirmed this by enabling the debug log and looking at the picture downloaded.

Is that something you can fix on your end? I'm not sure if it is an issue with camera entity in HA or with your camera code, as I do not know how the width/height of the screen is retrieved.
Either way, I'm open to suggestions if a fix is not possible in the integration.

Thanks!

**Comment by JiDW** [comment]
Not stale, good bot o/

**Comment by Daanoz** [comment]
I've not yet been able to reproduce your issue. The dimension to be requested is set by the [HA frontend code](https://github.com/home-assistant/frontend/blob/master/src/panels/lovelace/components/hui-image.ts#L368), which looks like it is taking the pixel ratio into account. Do you have other integrations that display the resolution correctly?
