### ISSUE TITLE
Google Photos are no longer loaded after approx. 1 day. 

### ISSUE THREAD

**Issue by Aquilord** [Daanoz/ha-google-photos#46]
Hello, 

after I set up Google Photos again, everything works for about 1 day and the pictures are displayed. After approx. 1 day. no more pictures are displayed. No error message or similar appears. I have already set up google photos several times and even created new login details. 

Unfortunately I have not found any other case for this problem. Can anyone here help me?

**Comment by Daanoz** [comment]
Could you try enabling more debug logging?

https://github.com/daanoz/ha-google-photos?tab=readme-ov-file#debug-logging

**Comment by Aquilord** [comment]
Hello Daanoz, 

Thank you for your answer. I have activated debug logging, but do not see any further error information in the log files. 

Or where could I see this?
