### ISSUE TITLE
WallPanel Addon Black Screen

### ISSUE THREAD

**Issue by TheCregLord** [Daanoz/ha-google-photos#49]
When I integrate Google Photos into the WallPanel add on it only shows a black screen. Attached is my code.
![image](https://github.com/Daanoz/ha-google-photos/assets/162933358/fe31e4d2-03ac-40b3-ab6d-87dae2f3096b)

**Comment by Daanoz** [comment]
Did you already try to remove the space in the image_url? (After media-entity://)

**Comment by TheCregLord** [comment]
I have no idea how I missed that, thank you that fixed.
