### ISSUE TITLE
Change update interval to an input_number

### ISSUE THREAD

**Issue by codemunkie15** [Daanoz/ha-google-photos#53]
Hi

Would you consider changing the update interval to an input number instead of a select please? 10 seconds is maxing out my Google API rate limit but 30 seconds seems like too long for my use case.

An input number would make it more flexible.

Many thanks

**Comment by Daanoz** [comment]
Although it gives maximum flexibility, changing that will probably cause a breaking change for everyone and I'm not sure if that works very nicely.

However, I will include a 20 second option in the next release. And there is always the option to disable the refresh ,and make a service call using an automation: https://github.com/Daanoz/ha-google-photos?tab=readme-ov-file#go-to-next-media.

**Comment by codemunkie15** [comment]
> Although it gives maximum flexibility, changing that will probably cause a breaking change for everyone and I'm not sure if that works very nicely.
> 
> However, I will include a 20 second option in the next release. And there is always the option to disable the refresh, and make a service call using an automation: https://github.com/Daanoz/ha-google-photos?tab=readme-ov-file#go-to-next-media.

Using the service is a great idea, thanks for the reminder :D
