### ISSUE TITLE
Navigate to previous

### ISSUE THREAD

**Issue by bonstio** [Daanoz/ha-google-photos#55]
We have a service for "Google Photos: Next media" but no way to get to the previous one.

When a photo rotates but someone didn't turn around quick enough, it's annoying that there's no way to go back. In an album with 20k photos, it will be a long time before that photo pops up again.

**Comment by Daanoz** [comment]
Due to API changes announced by Google, the integration will be deprecated on April 2025, so no new functionality will be added. https://github.com/Daanoz/ha-google-photos/issues/64
