### ISSUE TITLE
Add Location Data

### ISSUE THREAD

**Issue by mbler** [Daanoz/ha-google-photos#56]
Firstly, I love your integration! It's a great addition for home assistant.

My request:
The existing option "write metadata to attributes" already makes additional data available. However, I cannot find the location data, visible in Google Photos. It would be great to have access to the location data (if available) in home assistant. Thanks for considering the request.

**Comment by Daanoz** [comment]
Not possible:
https://github.com/Daanoz/ha-google-photos/issues/24
https://github.com/Daanoz/ha-google-photos/issues/38
