### ISSUE TITLE
Feature Request - Random but prioritize newer photos

### ISSUE THREAD

**Issue by trevornorcross** [Daanoz/ha-google-photos#60]
Other photo slideshow apps and devices (like Framee/Fotoo based devices) have an option in addition to ascending/descending order and "random" that is something like "Random but prioritizing newer photos". I couldn't tell you an exact algorithm, but when you add new photos it displays those more frequently than the others, yet still loads randomly. Would be great to get some newer photos shown a bit more often somehow.

**Comment by Daanoz** [comment]
Due to API changes announced by Google, the integration will be deprecated on April 2025, so no new functionality will be added. https://github.com/Daanoz/ha-google-photos/issues/64
