### ISSUE TITLE
Select photos by orientation. (portrait/landscape)

### ISSUE THREAD

**Issue by tharriso** [Daanoz/ha-google-photos#61]
I am using this addon with the lovelace wallpanel on tablets as digital photo frames. Really like it thank you.

There is not really a good crop for photos in a different orientation to the screen. 
It would be good if I could set a config so it only selects photos in either portrait or landscape.

What would be really deluxe is if it could match the current screen orientation, if that is knowable.

**Comment by Daanoz** [comment]
Due to API changes announced by Google, the integration will be deprecated on April 2025, so no new functionality will be added. https://github.com/Daanoz/ha-google-photos/issues/64
