### ISSUE TITLE
Detected that custom integration 'google_photos' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4

### ISSUE THREAD

**Issue by OrganicKobze** [Daanoz/ha-google-photos#62]
## Version of the custom_component

v0.6.3

## Configuration

```yaml

Normal Configuration

```

## Describe the bug
Detected that custom integration 'google_photos' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4;

This appears in HA logs.

## Debug log

```text

Detected that custom integration 'google_photos' calls `async_add_job`, which is deprecated and will be removed in Home Assistant 2025.4;

```

**Comment by Daanoz** [comment]
Due to API changes announced by Google, the integration will be deprecated on April 2025 anyway, so no use to fix this. https://github.com/Daanoz/ha-google-photos/issues/64
