### ISSUE TITLE
New Authorization Credentials

### ISSUE THREAD

**Issue by nicocoetzee** [Daanoz/ha-google-photos#8]
Hello -

My API settings changed and I need to re-enter them. I have removed and reinstalled the HACS & Integrations, but don't have the ability to enter the new info. 

When I install the new Integration it launches the Google page (https://accounts.google.com/signin/oauth/error/v2?authError...)

How do I update it?

I really appreciate any advice.

Many thanks,
N.

**Comment by Daanoz** [comment]
If you navigate to https://<your ha>/config/application_credentials (or click the 3 dot menu on the integrations screen) you can delete the credentials, and it will ask for new credentials when setting up the integration.

**Comment by nicocoetzee** [comment]
Thank you for the prompt response.
